baseurl = "http://www.brandonjd.net/"
languageCode = "en-US"
title = "Brandon Dusseau"
relativeURLs = false
canonifyURLs = false
disableRSS = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
# googleAnalytics = ""
theme = "brandonjd"
watch = true
